Added support for deprecated elements in ipp-registrations.xml
HPInc/jipp pull request #131
Opened 2022-10-21 17:29 UTC by HPNavjot

Addresses issue #130

2022-10-25 23:45 UTC, HPSudip requested changes
Looks good Navjot, just 2 comments.

2022-10-25 23:45 UTC, HPSudip commented on jipp-core/src/main/java/com/hp/jipp/model/Types.kt
> +    @JvmField val documentFormatDetails = AttributeCollection.Type("document-format-details", DocumentFormatDetails)
if we are bringing this code back we need to remove this line 
```
ignored_attributes = [
    # XML Fix (obsolete or maybe just deprecated)
    'document-format-details-supported'
]
```

in that case the -supported will also come.

2022-10-25 23:45 UTC, HPSudip commented on jipp-core/bin/genTypes.py
> +        if not (suffix.group(1) == 'extension' or suffix.group(1) == 'deprecated'):
Just extend the comment above

2022-10-26 11:48 UTC, HPNavjot commented on jipp-core/bin/genTypes.py
> +        if not (suffix.group(1) == 'extension' or suffix.group(1) == 'deprecated'):
Done

2022-10-27 00:35 UTC, HPSudip approved these changes

2022-10-27 06:22 UTC, merged